apiVersion: v1
kind: Pod
metadata: 
  name: tensorflow-test-pod
  labels: 
    app: demoApp
    
spec: 
  volumes: 
    - name: test-volume
      hostPath: 
        path: /home/cdlab-junior/dogs-vs-cats
        type: Directory
  containers:
    - name: tensorflow-demo-container
      image: nvcr.io/nvidia/tensorflow:19.10-py3
      command: ["/bash/sh", "-c"]
      args:
        - echo starting;
        cd /tmp/;
        python3 1124.yaml
        echo done;
      ports:
        - mountPath: /tmp
          name: test-volume
      resources:
        limits:
          nvidia.com/gpu: 1
  restartPolicy: Never
  nodeSelector:
    gpushare: "true"